<?php

return [
    'FORM_10' => [
        'rule' => 'Rule 26',
        'section' => 'Section 59',
        'act' => 'Tamil Nadu Factories Rules, 1950',
        'description' => 'Register of Overtime Work',
        'official_title' => 'Register of Overtime Work for Adults',
        'mandatory_headers' => ['establishment_name', 'period_month', 'period_year', 'license_number'],
        'required_row_fields' => ['employee_name', 'employee_id', 'overtime_hours', 'overtime_rate'],
        'column_sequence' => ['sl_no', 'employee_name', 'employee_id', 'date', 'overtime_hours', 'overtime_rate', 'overtime_wages'],
        'date_fields' => ['date'],
        'overtime_multiplier' => 2,
        'max_hours' => 50,
        'establishment_fields' => ['establishment_name', 'establishment_address', 'license_number'],
    ],
    'FORM_XVI' => [
        'rule' => 'Rule 78(1)(a)(i)',
        'section' => 'Section 29',
        'act' => 'Contract Labour (Regulation and Abolition) Central Rules, 1971',
        'description' => 'Register of Wages',
        'official_title' => 'Register of Wages (Contract Labour)',
        'mandatory_headers' => ['establishment_name', 'contractor_name', 'period_month', 'period_year', 'license_number'],
        'required_row_fields' => ['employee_name', 'employee_id', 'designation', 'wages'],
        'column_sequence' => ['sl_no', 'employee_name', 'employee_id', 'designation', 'days_worked', 'basic_wage', 'da', 'allowances', 'gross_wages', 'deductions', 'net_pay', 'signature'],
        'date_fields' => ['payment_date'],
        'min_wage' => 450,
        'esi_rate' => 0.75,
        'epf_rate' => 12,
        'check_child_labour' => true,
        'establishment_fields' => ['establishment_name', 'establishment_address', 'contractor_name', 'license_number'],
    ],
    'FORM_XVII' => [
        'rule' => 'Rule 78(1)(a)(ii)',
        'section' => 'Section 29',
        'act' => 'Contract Labour (Regulation and Abolition) Central Rules, 1971',
        'description' => 'Register of Deductions for Damage or Loss',
        'official_title' => 'Register of Deductions for Damage or Loss',
        'mandatory_headers' => ['establishment_name', 'contractor_name', 'period_month', 'period_year'],
        'required_row_fields' => ['employee_name', 'deduction_amount', 'reason'],
        'column_sequence' => ['sl_no', 'employee_name', 'employee_id', 'date', 'deduction_amount', 'reason', 'remarks'],
        'date_fields' => ['date'],
        'establishment_fields' => ['establishment_name', 'contractor_name'],
    ],
    'FORM_XIX' => [
        'rule' => 'Rule 78(1)(a)(iv)',
        'section' => 'Section 29',
        'act' => 'Contract Labour (Regulation and Abolition) Central Rules, 1971',
        'description' => 'Muster Roll',
        'official_title' => 'Muster Roll (Contract Labour)',
        'mandatory_headers' => ['establishment_name', 'contractor_name', 'period_month', 'period_year', 'work_order_number'],
        'required_row_fields' => ['employee_name', 'employee_id', 'attendance'],
        'column_sequence' => ['sl_no', 'employee_name', 'employee_id', 'designation', 'attendance', 'days_worked', 'remarks'],
        'check_child_labour' => true,
        'gender_required' => true,
        'establishment_fields' => ['establishment_name', 'contractor_name', 'work_order_number'],
    ],
    'FORM_XXIII' => [
        'rule' => 'Rule 78(1)(a)(viii)',
        'section' => 'Section 29',
        'act' => 'Contract Labour (Regulation and Abolition) Central Rules, 1971',
        'description' => 'Register of Overtime',
        'official_title' => 'Register of Overtime (Contract Labour)',
        'mandatory_headers' => ['establishment_name', 'contractor_name', 'period_month', 'period_year'],
        'required_row_fields' => ['employee_name', 'overtime_hours', 'overtime_rate'],
        'column_sequence' => ['sl_no', 'employee_name', 'employee_id', 'date', 'normal_hours', 'overtime_hours', 'overtime_rate', 'overtime_wages'],
        'date_fields' => ['date'],
        'overtime_multiplier' => 2,
        'max_hours' => 50,
        'establishment_fields' => ['establishment_name', 'contractor_name'],
    ],
    'SHOPS_FORM_12' => [
        'rule' => 'Rule 12',
        'section' => 'Section 18',
        'act' => 'Tamil Nadu Shops and Establishments Act, 1947',
        'description' => 'Register of Wages',
        'official_title' => 'Register of Wages (Shops & Establishments)',
        'mandatory_headers' => ['establishment_name', 'period_month', 'period_year', 'registration_number'],
        'required_row_fields' => ['employee_name', 'employee_id', 'wages'],
        'column_sequence' => ['sl_no', 'employee_name', 'employee_id', 'designation', 'days_worked', 'basic_wage', 'allowances', 'gross_wages', 'deductions', 'net_pay', 'signature'],
        'date_fields' => ['payment_date'],
        'min_wage' => 450,
        'establishment_fields' => ['establishment_name', 'establishment_address', 'registration_number'],
    ],
    'FORM_11' => [
        'rule' => 'Rule 99',
        'section' => 'Section 88',
        'act' => 'Tamil Nadu Factories Rules, 1950',
        'description' => 'Notice of Accident',
        'official_title' => 'Notice of Accident',
        'mandatory_headers' => ['establishment_name', 'accident_date', 'reported_date'],
        'required_row_fields' => ['employee_name', 'nature_of_injury', 'body_part_affected'],
        'date_fields' => ['accident_date', 'reported_date'],
        'establishment_fields' => ['establishment_name', 'factory_address'],
    ],
    'FORM_26' => [
        'rule' => 'Rule 100',
        'section' => 'Section 88',
        'act' => 'Tamil Nadu Factories Rules, 1950',
        'description' => 'Notice of Dangerous Occurrence',
        'official_title' => 'Notice of Dangerous Occurrence',
        'mandatory_headers' => ['establishment_name', 'occurrence_date', 'reported_date'],
        'date_fields' => ['occurrence_date', 'reported_date'],
        'establishment_fields' => ['establishment_name', 'factory_address'],
    ],
    'FORM_26A' => [
        'rule' => 'Rule 100A',
        'section' => 'Section 88A',
        'act' => 'Tamil Nadu Factories Rules, 1950',
        'description' => 'Notice of Certain Other Accidents',
        'official_title' => 'Notice of Certain Other Accidents',
        'mandatory_headers' => ['establishment_name', 'accident_date'],
        'date_fields' => ['accident_date'],
        'establishment_fields' => ['establishment_name'],
    ],
    'FORM_B' => [
        'rule' => 'Rule 26',
        'section' => 'Section 59',
        'act' => 'Tamil Nadu Factories Rules, 1950',
        'description' => 'Register of Wages',
        'official_title' => 'Register of Wages (Factories)',
        'mandatory_headers' => ['establishment_name', 'period_month', 'period_year', 'license_number'],
        'required_row_fields' => ['employee_name', 'employee_id', 'wages'],
        'column_sequence' => ['sl_no', 'employee_name', 'employee_id', 'designation', 'days_worked', 'basic_wage', 'da', 'allowances', 'gross_wages', 'epf_contribution', 'esi_contribution', 'other_deductions', 'total_deductions', 'net_pay', 'signature'],
        'date_fields' => ['payment_date'],
        'min_wage' => 450,
        'esi_rate' => 0.75,
        'epf_rate' => 12,
        'check_child_labour' => true,
        'establishment_fields' => ['establishment_name', 'establishment_address', 'license_number'],
    ],
    'FORM_25' => [
        'rule' => 'Rule 26',
        'section' => 'Section 59',
        'act' => 'Tamil Nadu Factories Rules, 1950',
        'description' => 'Muster Roll',
        'official_title' => 'Muster Roll (Factories)',
        'mandatory_headers' => ['establishment_name', 'period_month', 'period_year', 'license_number'],
        'required_row_fields' => ['employee_name', 'employee_id'],
        'column_sequence' => ['sl_no', 'employee_name', 'employee_id', 'designation', 'attendance', 'days_worked', 'remarks'],
        'check_child_labour' => true,
        'establishment_fields' => ['establishment_name', 'license_number'],
    ],
    'FORM_2' => [
        'rule' => 'Rule 25',
        'section' => 'Section 61',
        'act' => 'Tamil Nadu Factories Rules, 1950',
        'description' => 'Notice of Periods of Work for Adults',
        'official_title' => 'Notice of Periods of Work for Adults',
        'mandatory_headers' => ['establishment_name', 'effective_date'],
        'date_fields' => ['effective_date'],
        'establishment_fields' => ['establishment_name'],
    ],
    'SHOPS_FORM_13' => [
        'rule' => 'Rule 13',
        'section' => 'Section 19',
        'act' => 'Tamil Nadu Shops and Establishments Act, 1947',
        'description' => 'Register of Leave',
        'official_title' => 'Register of Leave',
        'mandatory_headers' => ['establishment_name', 'period_year'],
        'required_row_fields' => ['employee_name', 'leave_type'],
        'date_fields' => ['leave_from', 'leave_to'],
        'establishment_fields' => ['establishment_name'],
    ],
    'SHOPS_FORM_C' => [
        'rule' => 'Form C',
        'section' => 'Section 12',
        'act' => 'Payment of Bonus Act, 1965',
        'description' => 'Register of Bonus',
        'official_title' => 'Register of Bonus Payments',
        'mandatory_headers' => ['establishment_name', 'accounting_year'],
        'required_row_fields' => ['employee_name', 'bonus_amount'],
        'column_sequence' => ['sl_no', 'employee_name', 'employee_id', 'wages_for_bonus', 'bonus_amount', 'payment_date', 'signature'],
        'date_fields' => ['payment_date'],
        'establishment_fields' => ['establishment_name'],
    ],
    'SHOPS_FORM_VI' => [
        'rule' => 'Form VI',
        'section' => 'Section 13',
        'act' => 'Tamil Nadu Shops and Establishments Act, 1947',
        'description' => 'Register of Holidays',
        'official_title' => 'Register of Holidays',
        'mandatory_headers' => ['establishment_name', 'period_year'],
        'date_fields' => ['holiday_date'],
        'establishment_fields' => ['establishment_name'],
    ],
    'SHOPS_UNPAID' => [
        'rule' => 'Form C',
        'section' => 'Section 12',
        'act' => 'Payment of Bonus Act, 1965',
        'description' => 'Register of Unpaid Wages',
        'official_title' => 'Register of Unpaid Wages',
        'mandatory_headers' => ['establishment_name', 'period_month', 'period_year'],
        'required_row_fields' => ['employee_name', 'unpaid_amount', 'reason'],
        'establishment_fields' => ['establishment_name'],
    ],
    'ESI_FORM_12' => [
        'rule_name' => 'Tamil Nadu ESI Rule',
        'reference' => 'TN ESI Act Section XYZ',
        'official_title' => 'ESI Contribution Register',
        'mandatory_headers' => ['establishment_name', 'esi_code', 'period_month', 'period_year'],
        'required_row_fields' => ['employee_name', 'employee_id', 'esi_contribution'],
        'esi_rate' => 0.75,
        'establishment_fields' => ['establishment_name', 'esi_code'],
    ],
    'EPF_INSPECTION' => [
        'rule_name' => 'Tamil Nadu EPF Rule',
        'reference' => 'TN EPF Rule ABC',
        'official_title' => 'EPF Contribution Register',
        'mandatory_headers' => ['establishment_name', 'epf_code', 'period_month', 'period_year'],
        'required_row_fields' => ['employee_name', 'employee_id', 'epf_contribution'],
        'epf_rate' => 12,
        'establishment_fields' => ['establishment_name', 'epf_code'],
    ],
    'HAZARD_REG' => [
        'rule_name' => 'Tamil Nadu Hazard Register Rule',
        'reference' => 'TN Safety Rule 123',
        'official_title' => 'Hazard Identification Register',
        'mandatory_headers' => ['establishment_name', 'assessment_date'],
        'date_fields' => ['assessment_date'],
        'establishment_fields' => ['establishment_name'],
    ],
];
